- hosts: localhost
  tasks:
        - name: Docker image Build
          shell: 'docker image build -t quizapp /var/lib/jenkins/workspace/Capstone-CI'
        - name: Stop Docker Service
          shell : 'docker service rm quizapp'
          ignore_errors: yes
        - name: Docker Swarm
          shell: 'docker service create --name quizapp --replicas 1 --publish 18018:8080 quizapp'
  become: yes

